### ISSUE TITLE
Redis deployment issue.

### ISSUE THREAD

**Issue by ghost** [hybris/redis-boshrelease#2]
Hi,

We are working on setting up this redis cluster with sentinel on vSphere and it fails with the below error. We checked the sentinel.erb file and it is expecting an Elastic IP in the network spec.
Is it possible to deploy this release on vSphere at all. Your help is much appreciated.

  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)
     Done preparing deployment (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started preparing dns > Binding DNS. Done (00:00:01)

  Started preparing configuration > Binding configuration. Error filling in template `sentinel.conf.erb' for`redis_leader_z1/0' (line 62: Could not determine elastic IP via network spec: {:redis1=>#<OpenStruct ip="10.*.*.*", netmask="198.*.*.0", cloud_properties=#<OpenStruct fds="unlimited", name="VM Network VLAN752">, default=["dns", "gateway"], dns=["1._._._", "1._._._", "1._._._"], gateway="10._.*.1", dns_record_name="0.redis-leader-z1.redis1.redis-hybris.microbosh">})

Error 100: Error filling in template `sentinel.conf.erb' for`redis_leader_z1/0' (line 62: Could not determine elastic IP via network spec: {:redis1=>#<OpenStruct ip="10.*.*.*", netmask="198.*.*.0", cloud_properties=#<OpenStruct fds="unlimited", name="VM Network VLAN752">, default=["dns", "gateway"], dns=["1._._._", "1._._._", "1._._._"], gateway="10._.*.1", dns_record_name="0.redis-leader-z1.redis1.redis-hybris.microbosh">})

Thanks,
Guru.

**Comment by maksd** [comment]
Hi @GuruprakashS, I have created an issue in our ticket system to manage this, should be fix soon, monitor this repo for a new release.

**Comment by ghost** [comment]
We will try this and let you know if any issues.Thanks Max.
